/**
 * CLAUDE.md template functions.
 *
 * Each function takes the startup context and returns a complete Markdown
 * string. No external template engine — TypeScript template literals give
 * us full type safety and zero extra deps.
 *
 * Template authoring rules:
 * - Keep root CLAUDE.md under ~60 lines — Claude Code loads this every session
 * - Agent CLAUDE.md files can be longer; they're only injected on demand
 * - Use [POPULATED BY SYNC] markers for sections that `agent-env sync` fills in
 */

import { StartupContext, STAGE_LABELS, STAGE_TONE } from './schema.js'

// ─── Root CLAUDE.md ───────────────────────────────────────────────────────────

export function rootClaudeMd(ctx: StartupContext): string {
  const stageLine = `${STAGE_LABELS[ctx.stage]} — ${STAGE_TONE[ctx.stage]}`
  const priorityList = ctx.priorities
    .split(/[,\n]/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p, i) => `${i + 1}. ${p}`)
    .join('\n')

  return `# ${ctx.startupName} — Startup Context

## What We're Building
${ctx.pitch}

## Stage
${stageLine}

## Tech Stack
${ctx.stack}

## Ideal Customer
${ctx.icp}

## Current Priorities
${priorityList}
${ctx.bottleneck ? `\n## Biggest Bottleneck\n${ctx.bottleneck}` : ''}

---

## Agent Team

This project uses a specialized agent environment. Use these agents when
delegating work via the Task tool, or invoke them directly with a slash command.

| Command | Agent | Use for |
|---------|-------|---------|
| \`/coding\` | Coding Agent | Implementation, bugs, refactoring, code review, deploys |
| \`/research\` | Research Agent | Decisions, competitor analysis, library evaluation, tradeoffs |
| \`/marketing\` | Marketing Agent | Copy, content, messaging, positioning, pitch, launches |
| \`/ops\` | Ops Agent | Planning, tooling, admin, integrations, everything else |
| \`/route\` | Auto-router | Describe a task — the environment picks the right agent |
| \`/sync\` | Sync | Analyze the codebase and populate the coding agent's context |
| \`/sync-research\` | Sync | Research competitors and populate the research agent's context |

## Routing Rules
- Code / architecture / debugging → \`/coding\`
- Decisions / investigations / comparisons → \`/research\`
- Copy / content / messaging / positioning → \`/marketing\`
- Ambiguous → \`/route\` and let the environment decide

---
*Generated by agent-env on ${new Date().toISOString().slice(0, 10)}. Edit \`CLAUDE.local.md\` for personal overrides.*
`
}

// ─── Coding Agent CLAUDE.md ───────────────────────────────────────────────────

export function codingAgentClaudeMd(ctx: StartupContext): string {
  return `# ${ctx.startupName} — Coding Agent

## Role
You are the coding agent for ${ctx.startupName}. Your job is to implement,
debug, and maintain the codebase with full awareness of the product context
and architectural conventions established below.

After completing any significant task, append a one-line summary to the
**Session Log** section at the bottom of this file.

## Product Context
${ctx.pitch}

**Stage:** ${STAGE_LABELS[ctx.stage]}
**Implication:** ${STAGE_TONE[ctx.stage]}

## Tech Stack
${ctx.stack}

## Architecture Overview
[POPULATED BY SYNC — run \`agent-env sync\` after init to generate this from the codebase]

## Code Conventions
[POPULATED BY SYNC — initially: follow conventions present in the codebase; match the style of the surrounding file]

## Testing Approach
[POPULATED BY SYNC — initially: follow existing test patterns in the repo]

## Key Files & Entry Points
[POPULATED BY SYNC — initially: explore with \`ls\` and \`Glob\`]

## Known Gotchas
[Append here as you discover them]

## What This Agent Does NOT Handle
- Market research or competitive analysis → use \`/research\`
- Copy, content, or messaging → use \`/marketing\`
- Administrative or planning tasks → use \`/ops\`

---

## Session Log
*(append: \`YYYY-MM-DD: [decision or finding]\`)*

`
}

// ─── Research Agent CLAUDE.md ─────────────────────────────────────────────────

export function researchAgentClaudeMd(ctx: StartupContext): string {
  return `# ${ctx.startupName} — Research Agent

## Role
You are the research agent for ${ctx.startupName}. You maintain the
institutional memory of what has been investigated, what decisions were
made and why, and what approaches were considered and dismissed.

This file is append-only for findings. After each session, add to the
appropriate section. Do not delete old entries — they are the audit trail.

## Product Context
${ctx.pitch}

**Stage:** ${STAGE_LABELS[ctx.stage]}
**ICP:** ${ctx.icp}

## Competitive Landscape
[Not yet populated. Start a research session with \`/research investigate competitors\` to begin.]

## Technical Decisions Log
*(format: \`YYYY-MM-DD: [decision] — [rationale]\`)*

## Dismissed Approaches
*(format: \`YYYY-MM-DD: [what was dismissed] — [why]\`)*

## Open Questions
*(list of unresolved questions that need future investigation)*
- What is the competitive landscape for this space?
- What adjacent tools do our target users already have in their stack?

## What This Agent Does NOT Handle
- Writing code → use \`/coding\`
- Writing copy or content → use \`/marketing\`
- Operations or scheduling → use \`/ops\`

---

## Session Log
*(append: \`YYYY-MM-DD: [topic researched] — [summary finding]\`)*

`
}

// ─── Marketing Agent CLAUDE.md ────────────────────────────────────────────────

export function marketingAgentClaudeMd(ctx: StartupContext): string {
  return `# ${ctx.startupName} — Marketing Agent

## Role
You are the marketing agent for ${ctx.startupName}. You own positioning,
messaging, and all external communications. You know the ICP cold and you
write in the brand voice consistently.

After producing copy or making a positioning decision, append a summary
to the **Session Log** at the bottom of this file.

## Product Context
${ctx.pitch}

**Stage:** ${STAGE_LABELS[ctx.stage]}
**Implication for marketing:** ${STAGE_TONE[ctx.stage]}

## Ideal Customer Profile
${ctx.icp}

## Positioning
[POPULATED AS YOU WORK — what makes ${ctx.startupName} different from alternatives]

## Brand Voice
[POPULATED AS YOU WORK — tone, style, words we use / words we avoid]

## Active Channels
[POPULATED AS YOU WORK — where we're publishing and at what cadence]

## Key Messages
[POPULATED AS YOU WORK — the 3–5 things we say in every context]

## Copy Archive
[Link or append key pieces of copy here for reuse and tone consistency]

## What This Agent Does NOT Handle
- Writing code → use \`/coding\`
- Technical decisions or competitor analysis → use \`/research\`
- Operations or scheduling → use \`/ops\`

---

## Session Log
*(append: \`YYYY-MM-DD: [what was produced or decided]\`)*

`
}

// ─── Ops Agent CLAUDE.md ──────────────────────────────────────────────────────

export function opsAgentClaudeMd(ctx: StartupContext): string {
  return `# ${ctx.startupName} — Ops Agent

## Role
You are the ops agent for ${ctx.startupName}. You handle everything the
other specialized agents don't: planning, tooling, integrations, admin,
scheduling, and general problem-solving.

## Product Context
${ctx.pitch}

**Stage:** ${STAGE_LABELS[ctx.stage]}

## Current Priorities
${ctx.priorities}
${ctx.bottleneck ? `\n## Current Bottleneck\n${ctx.bottleneck}` : ''}

## Active Tools & Integrations
[POPULATED AS YOU WORK — tools, services, and integrations in use]

## What This Agent Does NOT Handle
- Writing or reviewing code → use \`/coding\`
- Technical research or decisions → use \`/research\`
- Copy, content, or messaging → use \`/marketing\`

---

## Session Log
*(append: \`YYYY-MM-DD: [task completed or decision made]\`)*

`
}

// ─── Claude Code Custom Commands ──────────────────────────────────────────────

export function codingCommand(ctx: StartupContext): string {
  return `You are now operating as the **Coding Agent** for ${ctx.startupName}.

Begin by reading \`.agent-env/agents/coding/CLAUDE.md\` to load your full context.
After completing the task, append a one-line summary to the Session Log in that file.

Task: $ARGUMENTS
`
}

export function researchCommand(ctx: StartupContext): string {
  return `You are now operating as the **Research Agent** for ${ctx.startupName}.

Begin by reading \`.agent-env/agents/research/CLAUDE.md\` to load your context and
understand what has already been investigated. After completing the task, append
findings to the appropriate section of that file.

Task: $ARGUMENTS
`
}

export function marketingCommand(ctx: StartupContext): string {
  return `You are now operating as the **Marketing Agent** for ${ctx.startupName}.

Begin by reading \`.agent-env/agents/marketing/CLAUDE.md\` to load your context,
ICP, and brand voice. After completing the task, append a summary to the Session Log.

Task: $ARGUMENTS
`
}

export function opsCommand(ctx: StartupContext): string {
  return `You are now operating as the **Ops Agent** for ${ctx.startupName}.

Begin by reading \`.agent-env/agents/ops/CLAUDE.md\` to load your context.
After completing the task, append a summary to the Session Log.

Task: $ARGUMENTS
`
}

export function syncCommand(ctx: StartupContext): string {
  return `You are updating the **Coding Agent** context for ${ctx.startupName}.

**What ${ctx.startupName} does:** ${ctx.pitch}
**Stack:** ${ctx.stack}

Your job: analyze the codebase in the current directory and fill in every
\`[POPULATED BY SYNC]\` section inside \`.agent-env/agents/coding/CLAUDE.md\`.
Do real work — read actual files, don't summarize from memory.

---

## Step 1 — Map the file structure

Run Glob with pattern \`**/*\` to get all files. Exclude:
\`node_modules/**\`, \`.git/**\`, \`dist/**\`, \`build/**\`, \`.agent-env/**\`

Note the top-level directories and what each one likely contains.

## Step 2 — Read the entry points

Read \`package.json\`. Note:
- \`main\`, \`bin\`, \`exports\` fields (entry points)
- \`scripts\` (how to build, test, run)
- Key \`dependencies\` and \`devDependencies\`

Read the primary entry point file(s) in full.
If \`tsconfig.json\` exists, read it — note \`strict\`, \`module\`, \`target\`, \`paths\`.

## Step 3 — Find the architectural core

Use Grep to search for \`from '\` across all source files. The internal
modules imported most frequently are the architectural core — read them.

Aim to read at least 5 source files from different parts of the codebase.

## Step 4 — Find the tests

Glob for \`**/*.test.*\`, \`**/*.spec.*\`, \`**/__tests__/**\`.
Read 1-2 test files. Note: framework (jest/vitest/node:test), file naming
convention, what gets mocked vs tested directly, assertion style.

## Step 5 — Write the findings

Open \`.agent-env/agents/coding/CLAUDE.md\` and replace each
\`[POPULATED BY SYNC]\` marker with real content:

**Architecture Overview** — 3-5 short paragraphs. What are the main layers?
How does a request/task flow through the system? What are the boundaries
between modules? Name specific files and directories.

**Code Conventions** — Bulleted list, specific not generic. Examples:
- "ESM imports, .js extensions on all local imports"
- "Errors thrown, not returned as values"
- "No default exports — named exports only"
- "Zod for all external input validation"

**Testing Approach** — Framework, file naming pattern, what's unit-tested
vs integration-tested, any mocking patterns used.

**Key Files & Entry Points** — Markdown table: \`| path | purpose |\`
List the 6-10 files a new developer needs to understand first.

## Step 6 — Append to Session Log

Add this line to the Session Log at the bottom of the coding agent file:
\`${new Date().toISOString().slice(0, 10)}: /sync completed — architecture, conventions, testing, key files populated.\`

$ARGUMENTS
`
}

export function syncResearchCommand(ctx: StartupContext): string {
  return `You are updating the **Research Agent** context for ${ctx.startupName}.

**What ${ctx.startupName} does:** ${ctx.pitch}
**ICP:** ${ctx.icp}
**Stage:** ${STAGE_LABELS[ctx.stage]}

Your job: research the competitive landscape and populate the empty sections
inside \`.agent-env/agents/research/CLAUDE.md\`. Read what's already there
first — never duplicate existing entries.

---

## Step 1 — Read existing context

Read \`.agent-env/agents/research/CLAUDE.md\` in full. Note:
- Which competitors are already documented
- Which open questions are already listed
- Which decisions have already been logged

Only add new information.

## Step 2 — Research direct competitors

Use WebSearch to find tools that solve the same problem for the same ICP.
Try these searches (adapt to the actual product):
- \`"${ctx.startupName}" alternatives\`
- \`${ctx.pitch.slice(0, 60)} tools\`
- \`best [product category] for [ICP description] 2025\`

For each competitor found, use WebFetch to get their homepage or pricing page.
Document the ones that matter — aim for 3-6 direct competitors.

## Step 3 — Research adjacent tools

Search for tools that overlap but approach the problem differently — different
ICP, different angle, different layer of the stack. These matter for
positioning even if they're not direct competitors.

## Step 4 — Write the Competitive Landscape section

Open \`.agent-env/agents/research/CLAUDE.md\` and add to the
**Competitive Landscape** section. Format each competitor as:

\`\`\`
### [Competitor Name]
[One-line description] | [Pricing model] | [Target customer]

**Strengths:** [what they do well]
**Weaknesses:** [their gap — the opening for ${ctx.startupName}]
**vs ${ctx.startupName}:** [key differentiator]
\`\`\`

## Step 5 — Update Open Questions

Based on what you found, append 2-3 new questions worth investigating.
Format: \`- [Question]?\`

## Step 6 — Append to Session Log

Add this line to the Session Log:
\`${new Date().toISOString().slice(0, 10)}: /sync-research completed — competitive landscape populated.\`

$ARGUMENTS
`
}

export function routeCommand(_ctx: StartupContext): string {
  return `Analyze the following task and route it to the correct specialized agent.

**Routing rules:**
- Code / implementation / bugs / tests / deployment → \`/coding\`
- Research / decisions / comparisons / tradeoffs / "should we" → \`/research\`
- Copy / content / messaging / positioning / launches → \`/marketing\`
- Everything else → \`/ops\`

Once you've decided, activate the agent using its slash command and execute the task.
Show your routing reasoning before activating.

Task: $ARGUMENTS
`
}
